/* Generated by sharpc. Do not edit by hand. */
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#include <malloc.h>
typedef int32_t errno_t;
typedef uint16_t _ino_t;
typedef uint16_t ino_t;
typedef uint32_t _dev_t;
typedef uint32_t dev_t;
typedef int32_t _pid_t;
typedef int32_t pid_t;
typedef uint16_t _mode_t;
typedef uint16_t mode_t;
typedef int64_t _off_t;
typedef int64_t off_t;
typedef int64_t _off64_t;
typedef int64_t off64_t;
typedef struct timespec timespec;
typedef struct itimerspec itimerspec;

extern uint64_t _beginthread(void* p0, unsigned _StackSize, void* _ArgList);
extern void _endthread(void);
extern uint64_t _beginthreadex(void* _Security, unsigned _StackSize, unsigned* p2, void* _ArgList, unsigned _InitFlag, unsigned* _ThrdAddr);
extern void _endthreadex(unsigned _Retval);
extern void exit(int32_t _Code);
extern void _exit(int32_t _Code);
extern void abort(void);
extern void _cexit(void);
extern void _c_exit(void);
extern int32_t _getpid(void);
extern int64_t _cwait(int32_t* _TermStat, int64_t _ProcHandle, int32_t _Action);
extern int64_t _execl(const int8_t* _Filename, const int8_t* _ArgList);
extern int64_t _execle(const int8_t* _Filename, const int8_t* _ArgList);
extern int64_t _execlp(const int8_t* _Filename, const int8_t* _ArgList);
extern int64_t _execlpe(const int8_t* _Filename, const int8_t* _ArgList);
extern int64_t _execv(const int8_t* _Filename, const int8_t* const* _ArgList);
extern int64_t _execve(const int8_t* _Filename, const int8_t* const* _ArgList, const int8_t* const* _Env);
extern int64_t _execvp(const int8_t* _Filename, const int8_t* const* _ArgList);
extern int64_t _execvpe(const int8_t* _Filename, const int8_t* const* _ArgList, const int8_t* const* _Env);
extern int64_t _spawnl(int32_t _Mode, const int8_t* _Filename, const int8_t* _ArgList);
extern int64_t _spawnle(int32_t _Mode, const int8_t* _Filename, const int8_t* _ArgList);
extern int64_t _spawnlp(int32_t _Mode, const int8_t* _Filename, const int8_t* _ArgList);
extern int64_t _spawnlpe(int32_t _Mode, const int8_t* _Filename, const int8_t* _ArgList);
extern int64_t _spawnv(int32_t _Mode, const int8_t* _Filename, const int8_t* const* _ArgList);
extern int64_t _spawnve(int32_t _Mode, const int8_t* _Filename, const int8_t* const* _ArgList, const int8_t* const* _Env);
extern int64_t _spawnvp(int32_t _Mode, const int8_t* _Filename, const int8_t* const* _ArgList);
extern int64_t _spawnvpe(int32_t _Mode, const int8_t* _Filename, const int8_t* const* _ArgList, const int8_t* const* _Env);
extern int32_t system(const int8_t* _Command);
extern int64_t _wexecl(int32_t* _Filename, int32_t* _ArgList);
extern int64_t _wexecle(int32_t* _Filename, int32_t* _ArgList);
extern int64_t _wexeclp(int32_t* _Filename, int32_t* _ArgList);
extern int64_t _wexeclpe(int32_t* _Filename, int32_t* _ArgList);
extern int64_t _wexecv(int32_t* _Filename, int32_t* const* _ArgList);
extern int64_t _wexecve(int32_t* _Filename, int32_t* const* _ArgList, int32_t* const* _Env);
extern int64_t _wexecvp(int32_t* _Filename, int32_t* const* _ArgList);
extern int64_t _wexecvpe(int32_t* _Filename, int32_t* const* _ArgList, int32_t* const* _Env);
extern int64_t _wspawnl(int32_t _Mode, int32_t* _Filename, int32_t* _ArgList);
extern int64_t _wspawnle(int32_t _Mode, int32_t* _Filename, int32_t* _ArgList);
extern int64_t _wspawnlp(int32_t _Mode, int32_t* _Filename, int32_t* _ArgList);
extern int64_t _wspawnlpe(int32_t _Mode, int32_t* _Filename, int32_t* _ArgList);
extern int64_t _wspawnv(int32_t _Mode, int32_t* _Filename, int32_t* const* _ArgList);
extern int64_t _wspawnve(int32_t _Mode, int32_t* _Filename, int32_t* const* _ArgList, int32_t* const* _Env);
extern int64_t _wspawnvp(int32_t _Mode, int32_t* _Filename, int32_t* const* _ArgList);
extern int64_t _wspawnvpe(int32_t _Mode, int32_t* _Filename, int32_t* const* _ArgList, int32_t* const* _Env);
extern int32_t _wsystem(int32_t* _Command);
extern void __security_init_cookie(void);
extern void __security_check_cookie(uint64_t _StackCookie);
extern void __report_gsfailure(void);
extern int64_t _loaddll(int8_t* _Filename);
extern int32_t _unloaddll(int64_t _Handle);
extern int32_t (*_getdllprocaddr(void p))();
extern int64_t cwait(int32_t* _TermStat, int64_t _ProcHandle, int32_t _Action);
extern int64_t execl(const int8_t* _Filename, const int8_t* _ArgList);
extern int64_t execle(const int8_t* _Filename, const int8_t* _ArgList);
extern int64_t execlp(const int8_t* _Filename, const int8_t* _ArgList);
extern int64_t execlpe(const int8_t* _Filename, const int8_t* _ArgList);
extern int64_t spawnl(int32_t p0, const int8_t* _Filename, const int8_t* _ArgList);
extern int64_t spawnle(int32_t p0, const int8_t* _Filename, const int8_t* _ArgList);
extern int64_t spawnlp(int32_t p0, const int8_t* _Filename, const int8_t* _ArgList);
extern int64_t spawnlpe(int32_t p0, const int8_t* _Filename, const int8_t* _ArgList);
extern int32_t getpid(void);
extern int64_t execv(const int8_t* _Filename, const int8_t* const* _ArgList);
extern int64_t execve(const int8_t* _Filename, const int8_t* const* _ArgList, const int8_t* const* _Env);
extern int64_t execvp(const int8_t* _Filename, const int8_t* const* _ArgList);
extern int64_t execvpe(const int8_t* _Filename, const int8_t* const* _ArgList, const int8_t* const* _Env);
extern int64_t spawnv(int32_t p0, const int8_t* _Filename, const int8_t* const* _ArgList);
extern int64_t spawnve(int32_t p0, const int8_t* _Filename, const int8_t* const* _ArgList, const int8_t* const* _Env);
extern int64_t spawnvp(int32_t p0, const int8_t* _Filename, const int8_t* const* _ArgList);
extern int64_t spawnvpe(int32_t p0, const int8_t* _Filename, const int8_t* const* _ArgList, int8_t* const* _Env);
extern uint64_t __security_cookie;


struct timespec {
    int64_t tv_sec;
    int64_t tv_nsec;
};

struct itimerspec {
    struct timespec it_interval;
    struct timespec it_value;
};

