/* Generated by sharpc. Do not edit by hand. */
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>


int32_t main(void);

int32_t main(void) {
    int32_t sum = 0;
    int32_t i = 0;
    while ((i < 5))
    {
        (sum = (sum + i));
        (i = (i + 1));
    }
    return sum;
}

