/* Generated by sharpc. Do not edit by hand. */
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
typedef int8_t   i8;
typedef int16_t  i16;
typedef int32_t  i32;
typedef int64_t  i64;
typedef uint8_t  u8;
typedef uint16_t u16;
typedef uint32_t u32;
typedef uint64_t u64;
typedef float    f32;
typedef double   f64;
typedef intptr_t isize;
typedef uintptr_t usize;


static i32 add(i32 a, i32 b);
static i32 sub(i32 a, i32 b);
static i32 mul(i32 a, i32 b);
static i32 abs_val(i32 x);
static i32 clamp(i32 x, i32 min, i32 max);
i32 main(void);

static i32 add(i32 a, i32 b) {
    return (a + b);
}

static i32 sub(i32 a, i32 b) {
    return (a - b);
}

static i32 mul(i32 a, i32 b) {
    return (a * b);
}

static i32 abs_val(i32 x) {
    if ((x < 0)) {
        return (-x);
    }
    return x;
}

static i32 clamp(i32 x, i32 min, i32 max) {
    if ((x < min)) 
        return min;
    if ((x > max)) 
        return max;
    return x;
}

i32 main(void) {
    i32 a = 10;
    i32 b = 20;
    i32 sum = add(a, b);
    i32 diff = sub(sum, b);
    i32 product = mul(diff, b);
    i32 neg = sub(0, 50);
    i32 abs = abs_val(neg);
    i32 clamped = clamp(product, 0, 150);
    i32 result = add(sum, add(abs, clamped));
    return result;
}

