/* Generated by sharpc. Do not edit by hand. */
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>


static int add(int a, int b);
static int sub(int a, int b);
static int mul(int a, int b);
static int abs_val(int x);
static int clamp(int x, int min, int max);
static int add2(int a, int b);
int main(void);

static int add(int a, int b) {
    return (a + b);
}

static int sub(int a, int b) {
    return (a - b);
}

static int mul(int a, int b) {
    return (a * b);
}

static int abs_val(int x) {
    if ((x < 0)) {
        return (-x);
    }
    return x;
}

static int clamp(int x, int min, int max) {
    if ((x < min)) 
        return min;
    if ((x > max)) 
        return max;
    return x;
}

static int add2(int a, int b) {
    return (a + b);
}

int main(void) {
    int a = 10;
    int b = 20;
    int sum = add2(a, b);
    int diff = sub(sum, b);
    int product = mul(diff, b);
    int neg = sub(0, 50);
    int abs = abs_val(neg);
    int clamped = clamp(product, 0, 150);
    int result = add(sum, add(abs, clamped));
    return result;
}

