/* Generated by sharpc. Do not edit by hand. */
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

extern int printf(uint8_t* fmt);
extern int fprintf(FILE* file, uint8_t* fmt);
extern int sprintf(uint8_t* dest, uint8_t* fmt);
extern int snprintf(uint8_t* s, uintptr_t n, uint8_t* fmt);
extern int scanf(uint8_t* fmt);
extern int fscanf(FILE* file, uint8_t* fmt);
extern int sscanf(uint8_t* src, uint8_t* fmt);
extern FILE* fopen(uint8_t* filename, uint8_t* mode);
extern FILE* freopen(uint8_t* filename, uint8_t* mode, FILE* file);
extern int fclose(FILE* file);
extern int fgetc(FILE* file);
extern int fputc(int ch, FILE* file);
extern int getchar(void);
extern int putchar(int ch);
extern int getc(FILE* file);
extern int putc(int ch, FILE* file);
extern int ungetc(int ch, FILE* file);
extern uint8_t* fgets(uint8_t* buf, int maxcount, FILE* file);
extern int fputs(uint8_t* str, FILE* file);
extern int puts(uint8_t* str);
extern uintptr_t fread(void* dst, uintptr_t size, uintptr_t count, FILE* file);
extern uintptr_t fwrite(void* src, uintptr_t size, uintptr_t count, FILE* file);
extern int fseek(FILE* file, long long offset, int origin);
extern long long ftell(FILE* file);
extern void rewind(FILE* file);
extern int fgetpos(FILE* file, void* pos);
extern int fsetpos(FILE* file, void* pos);
extern int fflush(FILE* file);
extern int feof(FILE* file);
extern int ferror(FILE* file);
extern void clearerr(FILE* file);
extern void perror(uint8_t* msg);
extern void setbuf(FILE* file, uint8_t* buf);
extern int setvbuf(FILE* file, uint8_t* buf, int mode, uintptr_t size);
extern int remove(uint8_t* filename);
extern int rename(uint8_t* oldname, uint8_t* newname);
extern FILE* tmpfile(void);
extern uint8_t* tmpnam(uint8_t* buf);



