/* Generated by sharpc. Do not edit by hand. */
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdio.h>

extern int printf(char* fmt);
extern int fprintf(FILE* file, char* fmt);
extern int sprintf(char* dest, char* fmt);
extern int snprintf(char* s, uintptr_t n, char* fmt);
extern int scanf(char* fmt);
extern int fscanf(FILE* file, char* fmt);
extern int sscanf(char* src, char* fmt);
extern FILE* fopen(char* filename, char* mode);
extern FILE* freopen(char* filename, char* mode, FILE* file);
extern int fclose(FILE* file);
extern int fgetc(FILE* file);
extern int fputc(int ch, FILE* file);
extern int getchar(void);
extern int putchar(int ch);
extern int getc(FILE* file);
extern int putc(int ch, FILE* file);
extern int ungetc(int ch, FILE* file);
extern char* fgets(char* buf, int maxcount, FILE* file);
extern int fputs(char* str, FILE* file);
extern int puts(char* str);
extern uintptr_t fread(void* dst, uintptr_t size, uintptr_t count, FILE* file);
extern uintptr_t fwrite(void* src, uintptr_t size, uintptr_t count, FILE* file);
extern int fseek(FILE* file, long long offset, int origin);
extern long long ftell(FILE* file);
extern void rewind(FILE* file);
extern int fgetpos(FILE* file, void* pos);
extern int fsetpos(FILE* file, void* pos);
extern int fflush(FILE* file);
extern int feof(FILE* file);
extern int ferror(FILE* file);
extern void clearerr(FILE* file);
extern void perror(char* msg);
extern void setbuf(FILE* file, char* buf);
extern int setvbuf(FILE* file, char* buf, int mode, uintptr_t size);
extern int remove(char* filename);
extern int rename(char* oldname, char* newname);
extern FILE* tmpfile(void);
extern char* tmpnam(char* buf);


int main(void);

int main(void) {
    puts("Hello from Sharp!");
    return 0;
}

