/* Generated by sharpc. Do not edit by hand. */
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdio.h>

extern int g_count;
extern int* g_array;
extern int g_stdio_var;

int main(void);

int main(void) {
    return 0;
}

