/* Generated by sharpc. Do not edit by hand. */
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdio.h>


int main(void);

int main(void) {
    putc(72, stdout);
    putc(101, stdout);
    putc(108, stdout);
    putc(108, stdout);
    putc(111, stdout);
    putc(10, stdout);
    return 0;
}

