/* Generated by sharpc. Do not edit by hand. */
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

extern int c_add(int a, int b);
extern int c_mul(int a, int b);
extern void c_nothing(void p);


int main(void);

int main(void) {
    int a = 10;
    int b = 20;
    int sum = c_add(a, b);
    int product = c_mul(sum, b);
    int max = 100;
    return product;
}

