
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.2/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:6 (project)"
    message: |
      The system is: Windows - 10.0.19045 - AMD64
  -
    kind: "find-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.2/Modules/CMakeMinGWFindMake.cmake:5 (find_program)"
      - "CMakeLists.txt:6 (project)"
    mode: "program"
    variable: "CMAKE_MAKE_PROGRAM"
    description: "Path to a program."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "mingw32-make.exe"
    candidate_directories:
      - "C:/Users/ftp/AppData/Local/Programs/Microsoft VS Code/"
      - "C:/Users/ftp/AppData/Local/Programs/Python/Python313/"
      - "C:/Users/ftp/AppData/Local/Programs/Python/Python313/Scripts/"
      - "C:/Program Files (x86)/VMware/VMware Workstation/bin/"
      - "C:/Windows/System32/"
      - "C:/Windows/"
      - "C:/Windows/System32/wbem/"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/"
      - "C:/Windows/System32/OpenSSH/"
      - "C:/Program Files/dotnet/"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/"
      - "C:/Program Files/TortoiseSVN/bin/"
      - "C:/Program Files/NVIDIA Corporation/NVIDIA app/NvDLISR/"
      - "C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common/"
      - "C:/Program Files/MySQL/MySQL Server 5.7/bin/"
      - "C:/env/"
      - "C:/Users/ftp/Desktop/sharp/XC:/msys64/clang64/bin/"
      - "C:/Users/ftp/Desktop/sharp/XC:/msys64/usr/bin/"
      - "C:/Program Files (x86)/Tencent/\u5fae\u4fe1web\u5f00\u53d1\u8005\u5de5\u5177/dll/"
      - "C:/Pro/"
      - "C:/Users/ftp/Desktop/sharp/ram Fi/"
      - "C:/Users/ftp/Desktop/sharp/es/CMake/bin/"
      - "C:/Program Files/Erlang OTP/bin/"
      - "C:/Program Files (x86)/NetSarang/Xshell 8/"
      - "C:/Program Files/TortoiseGit/bin/"
      - "C:/Program Files/AMD/AMDuProf/bin/"
      - "C:/Program Files/Git/cmd/"
      - "C:/Program Files/CMake/bin/"
      - "C:/Program Files/nodejs/"
      - "C:/Program Files/MySQL/MySQL Shell 8.0/bin/"
      - "C:/Users/ftp/AppData/Local/Programs/Python/Launcher/"
      - "C:/Users/ftp/AppData/Local/Microsoft/WindowsApps/"
      - "C:/Users/ftp/.dotnet/tools/"
      - "C:/Users/ftp/AppData/Local/Programs/Microsoft VS Code/bin/"
      - "C:/Users/ftp/AppData/Local/Programs/Lingma/bin/"
      - "C:/Users/ftp/AppData/Local/Microsoft/WinGet/Packages/Ninja-build.Ninja_Microsoft.Winget.Source_8wekyb3d8bbwe/"
      - "C:/Users/ftp/AppData/Roaming/npm/"
      - "/REGISTRY-NOTFOUND/bin/"
      - "c:/MinGW/bin/"
      - "/MinGW/bin/"
      - "/REGISTRY-NOTFOUND/MinGW/bin/"
    searched_directories:
      - "C:/Users/ftp/AppData/Local/Programs/Microsoft VS Code/mingw32-make.exe.com"
      - "C:/Users/ftp/AppData/Local/Programs/Microsoft VS Code/mingw32-make.exe"
      - "C:/Users/ftp/AppData/Local/Programs/Python/Python313/mingw32-make.exe.com"
      - "C:/Users/ftp/AppData/Local/Programs/Python/Python313/mingw32-make.exe"
      - "C:/Users/ftp/AppData/Local/Programs/Python/Python313/Scripts/mingw32-make.exe.com"
      - "C:/Users/ftp/AppData/Local/Programs/Python/Python313/Scripts/mingw32-make.exe"
      - "C:/Program Files (x86)/VMware/VMware Workstation/bin/mingw32-make.exe.com"
      - "C:/Program Files (x86)/VMware/VMware Workstation/bin/mingw32-make.exe"
      - "C:/Windows/System32/mingw32-make.exe.com"
      - "C:/Windows/System32/mingw32-make.exe"
      - "C:/Windows/mingw32-make.exe.com"
      - "C:/Windows/mingw32-make.exe"
      - "C:/Windows/System32/wbem/mingw32-make.exe.com"
      - "C:/Windows/System32/wbem/mingw32-make.exe"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/mingw32-make.exe.com"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/mingw32-make.exe"
      - "C:/Windows/System32/OpenSSH/mingw32-make.exe.com"
      - "C:/Windows/System32/OpenSSH/mingw32-make.exe"
      - "C:/Program Files/dotnet/mingw32-make.exe.com"
      - "C:/Program Files/dotnet/mingw32-make.exe"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/mingw32-make.exe.com"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/mingw32-make.exe"
      - "C:/Program Files/TortoiseSVN/bin/mingw32-make.exe.com"
      - "C:/Program Files/TortoiseSVN/bin/mingw32-make.exe"
      - "C:/Program Files/NVIDIA Corporation/NVIDIA app/NvDLISR/mingw32-make.exe.com"
      - "C:/Program Files/NVIDIA Corporation/NVIDIA app/NvDLISR/mingw32-make.exe"
      - "C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common/mingw32-make.exe.com"
      - "C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common/mingw32-make.exe"
      - "C:/Program Files/MySQL/MySQL Server 5.7/bin/mingw32-make.exe.com"
      - "C:/Program Files/MySQL/MySQL Server 5.7/bin/mingw32-make.exe"
      - "C:/env/mingw32-make.exe.com"
      - "C:/env/mingw32-make.exe"
      - "C:/Users/ftp/Desktop/sharp/XC:/msys64/clang64/bin/mingw32-make.exe.com"
      - "C:/Users/ftp/Desktop/sharp/XC:/msys64/clang64/bin/mingw32-make.exe"
      - "C:/Users/ftp/Desktop/sharp/XC:/msys64/usr/bin/mingw32-make.exe.com"
      - "C:/Users/ftp/Desktop/sharp/XC:/msys64/usr/bin/mingw32-make.exe"
      - "C:/Program Files (x86)/Tencent/\u5fae\u4fe1web\u5f00\u53d1\u8005\u5de5\u5177/dll/mingw32-make.exe.com"
      - "C:/Program Files (x86)/Tencent/\u5fae\u4fe1web\u5f00\u53d1\u8005\u5de5\u5177/dll/mingw32-make.exe"
      - "C:/Pro/mingw32-make.exe.com"
      - "C:/Pro/mingw32-make.exe"
      - "C:/Users/ftp/Desktop/sharp/ram Fi/mingw32-make.exe.com"
      - "C:/Users/ftp/Desktop/sharp/ram Fi/mingw32-make.exe"
      - "C:/Users/ftp/Desktop/sharp/es/CMake/bin/mingw32-make.exe.com"
      - "C:/Users/ftp/Desktop/sharp/es/CMake/bin/mingw32-make.exe"
      - "C:/Program Files/Erlang OTP/bin/mingw32-make.exe.com"
      - "C:/Program Files/Erlang OTP/bin/mingw32-make.exe"
      - "C:/Program Files (x86)/NetSarang/Xshell 8/mingw32-make.exe.com"
      - "C:/Program Files (x86)/NetSarang/Xshell 8/mingw32-make.exe"
      - "C:/Program Files/TortoiseGit/bin/mingw32-make.exe.com"
      - "C:/Program Files/TortoiseGit/bin/mingw32-make.exe"
      - "C:/Program Files/AMD/AMDuProf/bin/mingw32-make.exe.com"
      - "C:/Program Files/AMD/AMDuProf/bin/mingw32-make.exe"
      - "C:/Program Files/Git/cmd/mingw32-make.exe.com"
      - "C:/Program Files/Git/cmd/mingw32-make.exe"
      - "C:/Program Files/CMake/bin/mingw32-make.exe.com"
      - "C:/Program Files/CMake/bin/mingw32-make.exe"
      - "C:/Program Files/nodejs/mingw32-make.exe.com"
      - "C:/Program Files/nodejs/mingw32-make.exe"
      - "C:/Program Files/MySQL/MySQL Shell 8.0/bin/mingw32-make.exe.com"
      - "C:/Program Files/MySQL/MySQL Shell 8.0/bin/mingw32-make.exe"
      - "C:/Users/ftp/AppData/Local/Programs/Python/Launcher/mingw32-make.exe.com"
      - "C:/Users/ftp/AppData/Local/Programs/Python/Launcher/mingw32-make.exe"
      - "C:/Users/ftp/AppData/Local/Microsoft/WindowsApps/mingw32-make.exe.com"
      - "C:/Users/ftp/AppData/Local/Microsoft/WindowsApps/mingw32-make.exe"
      - "C:/Users/ftp/.dotnet/tools/mingw32-make.exe.com"
      - "C:/Users/ftp/.dotnet/tools/mingw32-make.exe"
      - "C:/Users/ftp/AppData/Local/Programs/Microsoft VS Code/bin/mingw32-make.exe.com"
      - "C:/Users/ftp/AppData/Local/Programs/Microsoft VS Code/bin/mingw32-make.exe"
      - "C:/Users/ftp/AppData/Local/Programs/Lingma/bin/mingw32-make.exe.com"
      - "C:/Users/ftp/AppData/Local/Programs/Lingma/bin/mingw32-make.exe"
      - "C:/Users/ftp/AppData/Local/Microsoft/WinGet/Packages/Ninja-build.Ninja_Microsoft.Winget.Source_8wekyb3d8bbwe/mingw32-make.exe.com"
      - "C:/Users/ftp/AppData/Local/Microsoft/WinGet/Packages/Ninja-build.Ninja_Microsoft.Winget.Source_8wekyb3d8bbwe/mingw32-make.exe"
      - "C:/Users/ftp/AppData/Roaming/npm/mingw32-make.exe.com"
      - "C:/Users/ftp/AppData/Roaming/npm/mingw32-make.exe"
      - "/REGISTRY-NOTFOUND/bin/mingw32-make.exe.com"
      - "/REGISTRY-NOTFOUND/bin/mingw32-make.exe"
      - "c:/MinGW/bin/mingw32-make.exe.com"
      - "c:/MinGW/bin/mingw32-make.exe"
      - "/MinGW/bin/mingw32-make.exe.com"
      - "/MinGW/bin/mingw32-make.exe"
      - "/REGISTRY-NOTFOUND/MinGW/bin/mingw32-make.exe.com"
      - "/REGISTRY-NOTFOUND/MinGW/bin/mingw32-make.exe"
    found: false
    search_context:
      ENV{PATH}:
        - "C:\\Users\\ftp\\AppData\\Local\\Programs\\Microsoft VS Code"
        - "C:\\Users\\ftp\\AppData\\Local\\Programs\\Python\\Python313"
        - "C:\\Users\\ftp\\AppData\\Local\\Programs\\Python\\Python313\\Scripts"
        - "C:\\Program Files (x86)\\VMware\\VMware Workstation\\bin\\"
        - "C:\\WINDOWS\\system32"
        - "C:\\WINDOWS"
        - "C:\\WINDOWS\\System32\\Wbem"
        - "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\"
        - "C:\\WINDOWS\\System32\\OpenSSH\\"
        - "C:\\Program Files\\dotnet\\"
        - "C:\\Program Files (x86)\\Windows Kits\\10\\Windows Performance Toolkit\\"
        - "C:\\Program Files\\TortoiseSVN\\bin"
        - "C:\\Program Files\\NVIDIA Corporation\\NVIDIA app\\NvDLISR"
        - "C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common"
        - "C:\\Program Files\\MySQL\\MySQL Server 5.7\\bin"
        - "C:\\env"
        - "XC:\\msys64\\clang64\\bin"
        - "XC:\\msys64\\usr\\bin"
        - "C:\\Program Files (x86)\\Tencent\\\u5fae\u4fe1web\u5f00\u53d1\u8005\u5de5\u5177\\dll"
        - "C:\\Pro"
        - "ram Fi"
        - "es\\CMake\\bin"
        - "C:\\Program Files\\Erlang OTP\\bin"
        - "C:\\Program Files (x86)\\NetSarang\\Xshell 8\\"
        - "C:\\Program Files\\TortoiseGit\\bin"
        - "C:\\Program Files\\AMD\\AMDuProf\\bin"
        - "C:\\Program Files\\Git\\cmd"
        - "C:\\Program Files\\CMake\\bin"
        - "C:\\Program Files\\nodejs\\"
        - "C:\\Program Files\\MySQL\\MySQL Shell 8.0\\bin\\"
        - "C:\\Users\\ftp\\AppData\\Local\\Programs\\Python\\Launcher\\"
        - "C:\\Users\\ftp\\AppData\\Local\\Microsoft\\WindowsApps"
        - "C:\\Users\\ftp\\.dotnet\\tools"
        - "C:\\Users\\ftp\\AppData\\Local\\Programs\\Microsoft VS Code\\bin"
        - "C:\\Users\\ftp\\AppData\\Local\\Programs\\Lingma\\bin"
        - "C:\\Users\\ftp\\AppData\\Local\\Microsoft\\WinGet\\Packages\\Ninja-build.Ninja_Microsoft.Winget.Source_8wekyb3d8bbwe"
        - "C:\\Users\\ftp\\AppData\\Roaming\\npm"
...
