/* Generated by sharpc. Do not edit by hand. */


extern char* strncpy(char* dest, char* src, long n);
extern void* memcpy(void* dest, const void* src, long n);
extern void* memmove(void* dest, const void* src, long n);

int main(void);

int main(void) {
    return 0;
}

