/* Generated by sharpc. Do not edit by hand. */
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

extern void qsort(void* base, size_t nmemb, size_t size, int32_t (*compar)(const void*, const void*));


int32_t main(void);

int32_t main(void) {
    return 0;
}

