/* Generated by sharpc. Do not edit by hand. */
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

typedef struct Box_i32 Box_i32;

int32_t main(void);
static int32_t Box_i32_get(Box_i32 self);

struct Box_i32 {
    int32_t value;
};

int32_t main(void) {
    Box_i32 b;
    (b.value = 42);
    return Box_i32_get(b);
}

static int32_t Box_i32_get(Box_i32 self) {
    return self.value;
}

