/* Generated by sharpc. Do not edit by hand. */
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

extern int32_t strlen(const int8_t* s);


int32_t main(void);

int32_t main(void) {
    int32_t* p = NULL;
    return 0;
}

