/* Generated by sharpc. Do not edit by hand. */

typedef void (*sighandler_t)(int);
typedef int (*cmp_fn)(const void *, const void *);
typedef int errno_t;
typedef int* Perrno_t;
typedef int **PPerrno_t;
typedef int int_array[10];

int main(void);

int main(void) {
    return 0;
}

