/* Generated by sharpc. Do not edit by hand. */
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

__attribute__((noreturn)) extern void exit(int32_t code);


int32_t main(void);

int32_t main(void) {
    return 0;
}

