/* Generated by sharpc. Do not edit by hand. */
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

extern int32_t printf(const int8_t* fmt);
extern int32_t scanf(const int8_t* fmt);
extern int32_t snprintf(int8_t* buf, size_t n, const int8_t* fmt);


int32_t main(void);

int32_t main(void) {
    return 0;
}

