/* Generated by sharpc. Do not edit by hand. */
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

extern int32_t puts(const uint8_t* s);


int32_t main(void);

int32_t main(void) {
    const uint8_t* msg1 = "hello const";
    puts(msg1);
    return 0;
}

