/* Generated by sharpc. Do not edit by hand. */
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

typedef struct Point Point;

int32_t main(void);

struct Point {
    int32_t x;
    int32_t y;
};

int32_t main(void) {
    struct Point* p = (&(struct Point){ .x = 1, .y = 2 });
    return 0;
}

