/* Generated by sharpc. Do not edit by hand. */

typedef struct Outer Outer;

int main(void);

struct Outer {
    int x;
    struct {
        int a;
        int b;
    };
    union {
        int c;
        double d;
    };
};

int main(void) {
    return 0;
}

