/* Generated by sharpc. Do not edit by hand. */
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

typedef int8_t __static_assert_i32[1];

int32_t main(void);

int32_t main(void) {
    return 42;
}

