/* Generated by sharpc. Do not edit by hand. */
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>


int32_t main(void);

int32_t main(void) {
    int32_t x = 42;
    int32_t* p = (&x);
    return (*p);
}

