/* Generated by sharpc. Do not edit by hand. */
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
typedef int8_t   i8;
typedef int16_t  i16;
typedef int32_t  i32;
typedef int64_t  i64;
typedef uint8_t  u8;
typedef uint16_t u16;
typedef uint32_t u32;
typedef uint64_t u64;
typedef float    f32;
typedef double   f64;
typedef intptr_t isize;
typedef uintptr_t usize;

extern i32 clearerr_s(void* stream);

_Static_assert(sizeof(int) >= 4, "int must be at least 4 bytes");




i32 main(void);

i32 main(void) {
    i32 err = 0;
    return 0;
}

