/* Generated by sharpc. Do not edit by hand. */
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

typedef struct Flags Flags;

int32_t main(void);

struct Flags {
    uint32_t a : 1;
    uint32_t b : 2;
    uint32_t c : 4;
    uint32_t d : 25;
};

int32_t main(void) {
    return 0;
}

