/* Generated by sharpc. Do not edit by hand. */

typedef struct Point Point;

int main(void);

struct Point {
    int x;
    int y;
};

int main(void) {
    struct Point p = {.x = 1, .y = 2};
    return 0;
}

