/* Generated by sharpc. Do not edit by hand. */
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

typedef int64_t my_ll;

int32_t main(void);

int32_t main(void) {
    int64_t x = 0;
    return 0;
}

