/* Generated by sharpc. Do not edit by hand. */
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

__declspec(dllimport) extern int32_t external_value;

int32_t main(void);

int32_t main(void) {
    return 0;
}

