/* Generated by sharpc. Do not edit by hand. */
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

extern void log_msg(const int8_t* msg);
__declspec(dllimport) extern int32_t external_value;


static int32_t add(int32_t a, int32_t b);
int32_t main(void);

static int32_t add(int32_t a, int32_t b) {
    return (a + b);
}

int32_t main(void) {
    int32_t x = add(1, 2);
    return 0;
}

