/* Generated by sharpc. Do not edit by hand. */
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>


int32_t main(void);

int32_t main(void) {
    int32_t arr[4];
    ((arr)[0] = 1);
    ((arr)[1] = 2);
    ((arr)[2] = 3);
    ((arr)[3] = 4);
    return ((arr)[0] + (arr)[3]);
}

