/* Generated by sharpc. Do not edit by hand. */
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

extern int8_t* strncpy(int8_t* dest, const int8_t* src, size_t n);
extern void* memcpy(void* dest, const void* src, size_t n);
extern void* memmove(void* dest, const void* src, size_t n);


int32_t main(void);

int32_t main(void) {
    return 0;
}

