/* Generated by sharpc. Do not edit by hand. */
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>


int32_t main(void);

int32_t main(void) {
    _Bool flag = 1;
    if (flag) {
        return 42;
    }
    return 0;
}

