/* Generated by sharpc. Do not edit by hand. */
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

__declspec(thread) int32_t tls_var1;

int32_t main(void);

int32_t main(void) {
    __declspec(thread) int32_t tls_var2 = 0;
    return (tls_var1 + tls_var2);
}

