/* Generated by sharpc. Do not edit by hand. */
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>



int32_t main(void);

int32_t main(void) {
    int32_t x = 42;
    size_t align = __alignof(x);
    return 0;
}

