/* Generated by sharpc. Do not edit by hand. */
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

typedef struct _iobuf _iobuf;

int32_t main(void);

struct _iobuf {
    int8_t* _ptr;
    int32_t _cnt;
    int8_t* _base;
    int32_t _flag;
};

int32_t main(void) {
    return 0;
}

