/* Generated by sharpc. Do not edit by hand. */
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

typedef struct Packed Packed;

int32_t main(void);

struct Packed {
    uint8_t a;
    int32_t b;
};

int32_t main(void) {
    return 0;
}

