/* Generated by sharpc. Do not edit by hand. */
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

extern void* _malloca(size_t size);
extern void _freea(void* p);


int32_t main(void);

int32_t main(void) {
    return 0;
}

