/* Generated by sharpc. Do not edit by hand. */
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

extern int32_t clearerr_s(void* stream);

typedef int32_t errno_t;

int32_t main(void);

int32_t main(void) {
    int32_t err = 0;
    return 0;
}

