/* Generated by sharpc. Do not edit by hand. */

typedef struct Flags Flags;

int main(void);

struct Flags {
    int a : 1;
    int b : 2;
    int c : 4;
    int d : 25;
};

int main(void) {
    return 0;
}

