/* Generated by sharpc. Do not edit by hand. */
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>


int32_t main(void);

int32_t main(void) {
    int32_t sum = 0;
    int32_t i = 0;
    while ((i < 10))
    {
        (i = (i + 1));
        if ((i == 3)) 
            continue;
        if ((i == 6)) 
            break;
        (sum = (sum + i));
    }
    return sum;
}

