/* Generated by sharpc. Do not edit by hand. */
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

typedef void (*sighandler_t)(int32_t);
typedef int32_t (*cmp_fn)(const void*, const void*);
typedef int32_t errno_t;
typedef int32_t* Perrno_t;
typedef int32_t** PPerrno_t;
typedef int32_t* int_array;

int32_t main(void);

int32_t main(void) {
    return 0;
}

