/* Generated by sharpc. Do not edit by hand. */
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

typedef struct Outer Outer;

int32_t main(void);

struct __anon_struct_1 {
    int32_t a;
    int32_t b;
};

typedef struct __anon_struct_1 __anon_struct_1;
union __anon_union_1 {
    int32_t c;
    double d;
};

typedef union __anon_union_1 __anon_union_1;
struct Outer {
    int32_t x;
    __anon_struct_1 __anon_struct_1;
    __anon_union_1 __anon_union_1;
};

int32_t main(void) {
    return 0;
}

