/* Generated by sharpc. Do not edit by hand. */
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>


int32_t main(void);

int32_t main(void) {
    uint64_t x;
    int64_t y;
    double z;
    void* p;
    return 0;
}

