/* Generated by sharpc. Do not edit by hand. */
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

typedef struct Outer Outer;

int32_t main(void);

struct Inner {
    int32_t a;
    int32_t b;
};

typedef struct Inner Inner;
struct Outer {
    int32_t x;
    Inner inner;
};

int32_t main(void) {
    return 0;
}

