/* Generated by sharpc. Do not edit by hand. */
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>


int32_t main(void);

int32_t main(void) {
    __try {
 int32_t x = 1;
 } __except(1) {
 }
 
    return 0;
}

