/* Generated by sharpc. Do not edit by hand. */
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

extern int32_t __cdecl cdecl_fn(int32_t a, int32_t b);
extern int32_t __stdcall stdcall_fn(int32_t x);
extern void __fastcall fast_fn(int32_t a, int32_t b);


int32_t main(void);

int32_t main(void) {
    int32_t* __unaligned ptr;
    return 0;
}

