/* Generated by sharpc. Do not edit by hand. */
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>


int32_t main(void);

int32_t main(void) {
    void* p = (void*)(-1);
    int32_t* ip = (int32_t*)4294967295;
    return 0;
}

