/* Generated by sharpc. Do not edit by hand. */
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>


int32_t main(void);

int32_t main(void) {
    int32_t a = 7;
    int32_t b = 3;
    int32_t c = (a + b);
    int32_t d = (a - b);
    int32_t e = (a * b);
    int32_t f = (a / b);
    int32_t g = (a % b);
    if ((((((c == 10) && (d == 4)) && (e == 21)) && (f == 2)) && (g == 1))) {
        return 1;
    }
    return 0;
}

