/* Generated by sharpc. Do not edit by hand. */
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

extern int32_t __cdecl printf(const int8_t* format);
extern void __stdcall ExitProcess(uint32_t exitCode);
extern int32_t __fastcall add(int32_t a, int32_t b);


int32_t main(void);

int32_t main(void) {
    return 0;
}

