/* Generated by sharpc. Do not edit by hand. */
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

typedef struct __anon_struct_0 Point;
typedef struct Node Node;
typedef struct Node Node;
typedef struct __anon_struct_0 __anon_struct_0;
typedef union Value Value;

int32_t main(void);

struct Node {
    int32_t data;
    struct Node* next;
};

struct __anon_struct_0 {
    int32_t x;
    int32_t y;
};

union Value {
    int32_t i;
    double d;
    int8_t* s;
};

int32_t main(void) {
    union Value v;
    struct Node n;
    __anon_struct_0 p;
    return 0;
}

