/* Generated by sharpc. Do not edit by hand. */
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
typedef int8_t   i8;
typedef int16_t  i16;
typedef int32_t  i32;
typedef int64_t  i64;
typedef uint8_t  u8;
typedef uint16_t u16;
typedef uint32_t u32;
typedef uint64_t u64;
typedef float    f32;
typedef double   f64;
typedef intptr_t isize;
typedef uintptr_t usize;

extern i32 puts(const u8* s);


i32 main(void);

i32 main(void) {
    const u8* msg1 = "hello const";
    puts(msg1);
    return 0;
}

