/* Generated by sharpc. Do not edit by hand. */
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

extern void fpclassify_impl(double x);
extern void fpclassify_impl_f(float x);


int32_t main(void);

int32_t main(void) {
    double x = 1.0;
    return 0;
}

