/* Generated by sharpc. Do not edit by hand. */
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
typedef int8_t   i8;
typedef int16_t  i16;
typedef int32_t  i32;
typedef int64_t  i64;
typedef uint8_t  u8;
typedef uint16_t u16;
typedef uint32_t u32;
typedef uint64_t u64;
typedef float    f32;
typedef double   f64;
typedef intptr_t isize;
typedef uintptr_t usize;

typedef struct Node Node;
typedef struct Node Node;
typedef struct __anon_struct_0 __anon_struct_0;
typedef union Value Value;

i32 main(void);

struct Node {
    i32 data;
    struct Node* next;
};

struct __anon_struct_0 {
    i32 x;
    i32 y;
};

typedef union Value {
    i32 i;
    f64 d;
    char* s;
} Value;

i32 main(void) {
    union Value v;
    struct Node n;
    __anon_struct_0 p;
    return 0;
}

