/* Generated by sharpc. Do not edit by hand. */

typedef struct Outer Outer;

int main(void);

struct Outer {
    int x;
    struct Inner {
        int a;
        int b;
    } inner;
};

int main(void) {
    return 0;
}

