/* Generated by sharpc. Do not edit by hand. */
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

typedef struct FlexArray FlexArray;

int32_t main(void);

struct FlexArray {
    int32_t len;
    int32_t data[1];
};

int32_t main(void) {
    return 0;
}

