/* Generated by sharpc. Do not edit by hand. */
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>


int32_t main(void);

int32_t main(void) {
    int32_t (*fp)(int32_t, int32_t) = NULL;
    return 0;
}

