/* Generated by sharpc. Do not edit by hand. */
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>


int32_t main(void);

int32_t main(void) {
    _Bool t = true;
    _Bool f = false;
    if ((t && (!f))) {
        return 1;
    }
    return 0;
}

