/* Generated by sharpc. Do not edit by hand. */
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>


double main(void);

double main(void) {
    double inf_val = (1.0 / 0.0);
    if ((inf_val > 1.0)) {
        return 42.0;
    }
    return 0.0;
}

