/* Generated by sharpc. Do not edit by hand. */
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

extern int32_t puts(const uint8_t* s);


static void print_msg(const uint8_t* msg);
int32_t main(void);

static void print_msg(const uint8_t* msg) {
    puts(msg);
}

int32_t main(void) {
    const uint8_t* hello = "hello";
    print_msg(hello);
    return 0;
}

