/* Generated by sharpc. Do not edit by hand. */
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

extern void* alloca(size_t size);
extern void* __builtin_alloca(size_t size);


int32_t main(void);

int32_t main(void) {
    int32_t* p = (int32_t*)alloca(100);
    return 0;
}

