/* Generated by sharpc. Do not edit by hand. */
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>


static int32_t add(int32_t a, int32_t b);
int32_t main(void);

static int32_t add(int32_t a, int32_t b) {
    return (a + b);
}

int32_t main(void) {
    return 0;
}

