/* Generated by sharpc. Do not edit by hand. */
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
typedef int8_t   i8;
typedef int16_t  i16;
typedef int32_t  i32;
typedef int64_t  i64;
typedef uint8_t  u8;
typedef uint16_t u16;
typedef uint32_t u32;
typedef uint64_t u64;
typedef float    f32;
typedef double   f64;
typedef intptr_t isize;
typedef uintptr_t usize;

extern i32 vprintf(char* format, void* args);


static i32 add(i32 a, i32 b);
i32 main(void);

static i32 add(i32 a, i32 b) {
    return (a + b);
}

i32 main(void) {
    void* args;
    i32 x = add(1, 2);
    return 0;
}

