/* Generated by sharpc. Do not edit by hand. */
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

typedef struct Vec2 Vec2;

static int32_t Vec2_sum(Vec2 self);
int32_t main(void);

struct Vec2 {
    int32_t x;
    int32_t y;
};

static int32_t Vec2_sum(Vec2 self) {
    return (self.x + self.y);
}

int32_t main(void) {
    Vec2 v;
    (v.x = 3);
    (v.y = 4);
    return Vec2_sum(v);
}

