/* Generated by sharpc. Do not edit by hand. */
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>


int32_t main(void);

int32_t main(void) {
    int32_t a = 42;
    int64_t b = 42;
    int16_t c = 42;
    int8_t d = 42;
    uint32_t e = 42;
    uint64_t f = 42;
    uint16_t g = 42;
    uint8_t h = 42;
    int64_t i = 42;
    int32_t j = 42;
    return a;
}

