/* Generated by sharpc. Do not edit by hand. */
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>


int32_t main(void);

int32_t main(void) {
    int32_t x = 5;
    if ((x > 3)) {
        return 1;
    }
    else {
        return 0;
    }
}

