#define TARGET(x)  target_##x
#define SIMPLE_BARE TARGET
#define DISPATCH_CALL(...) DISPATCH_CALL_IS_CALLABLE

SIMPLE_BARE

#ifdef DISPATCH_CALL
DISPATCH_CALL_IS_DEFINED
#else
DISPATCH_CALL_IS_NOT_DEFINED
#endif