/* Generated by sharpc. Do not edit by hand. */
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdio.h>

typedef struct Point Point;

static int factorial(int n);
static int fib(int n);
static int sum_to(int n);
static int count_even(int n);
int main(void);

struct Point {
    int x;
    int y;
};

static int factorial(int n) {
    if ((n <= 1)) {
        return 1;
    }
    return (n * factorial((n - 1)));
}

static int fib(int n) {
    if ((n < 2)) {
        return n;
    }
    return (fib((n - 1)) + fib((n - 2)));
}

static int sum_to(int n) {
    int total = 0;
    int i = 1;
    while ((i <= n))
    {
        (total = (total + i));
        (i = (i + 1));
    }
    return total;
}

static int count_even(int n) {
    int c = 0;
    {
        int i = 0;
        for (; (i < n); (i = (i + 1)))
        {
            if (((i % 2) == 0)) {
                (c = (c + 1));
            }
        }
    }
    return c;
}

int main(void) {
    int a = factorial(5);
    int b = fib(8);
    int c = sum_to(10);
    int d = count_even(10);
    int result = (((a - b) - c) - d);
    return result;
}

