/* Generated by sharpc. Do not edit by hand. */
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
typedef int8_t   i8;
typedef int16_t  i16;
typedef int32_t  i32;
typedef int64_t  i64;
typedef uint8_t  u8;
typedef uint16_t u16;
typedef uint32_t u32;
typedef uint64_t u64;
typedef float    f32;
typedef double   f64;
typedef intptr_t isize;
typedef uintptr_t usize;

typedef struct Point Point;

static i32 factorial(i32 n);
static i32 fib(i32 n);
static i32 sum_to(i32 n);
static i32 count_even(i32 n);
i32 main(void);

struct Point {
    i32 x;
    i32 y;
};

static i32 factorial(i32 n) {
    if ((n <= 1)) {
        return 1;
    }
    return (n * factorial((n - 1)));
}

static i32 fib(i32 n) {
    if ((n < 2)) {
        return n;
    }
    return (fib((n - 1)) + fib((n - 2)));
}

static i32 sum_to(i32 n) {
    i32 total = 0;
    i32 i = 1;
    while ((i <= n))
    {
        (total = (total + i));
        (i = (i + 1));
    }
    return total;
}

static i32 count_even(i32 n) {
    i32 c = 0;
    {
        i32 i = 0;
        for (; (i < n); (i = (i + 1)))
        {
            if (((i % 2) == 0)) {
                (c = (c + 1));
            }
        }
    }
    return c;
}

i32 main(void) {
    i32 a = factorial(5);
    i32 b = fib(8);
    i32 c = sum_to(10);
    i32 d = count_even(10);
    i32 result = (((a - b) - c) - d);
    return result;
}

