/* Generated by sharpc. Do not edit by hand. */
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdio.h>

extern int abs(int n);

typedef struct Box Box;

static Box Box_make(int v);
static void Box___drop(Box* self);
static int compute(int x);
int main(void);

struct Box {
    int val;
};

static Box Box_make(int v) {
    return (Box){ .val = v };
}

static void Box___drop(Box* self) {
}

static int compute(int x) {
    Box b = Box_make((x * 2));
    printf("%d\n", b.val);
    {
        int __ret_0 = b.val;
        Box___drop(&b);
        return __ret_0;
    }
}

int main(void) {
    printf("%d", 42);
    printf("%d\n", 0);
    printf("%s\n", (true) ? "true" : "false");
    printf("%s\n", (false) ? "true" : "false");
    int a = 40;
    int b = 30;
    printf("%d\n", a);
    printf("%d\n", b);
    int neg = (-20);
    int pos = abs(neg);
    printf("%d\n", pos);
    int c = compute(10);
    int x = 5;
    if ((x > 3)) {
        printf("%d\n", x);
    }
    int sum = 0;
    {
        int k = 0;
        for (; (k < 3); (k++))
        {
            (sum = (sum + k));
        }
    }
    printf("%d\n", sum);
    return ((((((a + b) + pos) + sum) + x) + c) - 19);
}

