/*
 * webgui_html.h — Embedded frontend page.
 *
 * Served via ws.h's HTTP fallback when a non-WebSocket request hits the
 * server root. Connects back to the same host as a WebSocket client.
 *
 * Protocol (JSON over WebSocket, UTF-8 text frames):
 *
 *   Server -> Client:
 *     { "type": "render", "title": "...", "icon": "...", "tree": <node> }
 *     { "type": "set_text",     "id": "...", "value": "..." }
 *     { "type": "set_value",    "id": "...", "value": "..." }
 *     { "type": "set_disabled", "id": "...", "value": true | false }
 *     { "type": "set_visible",  "id": "...", "value": true | false }
 *     { "type": "set_attr",     "id": "...", "key": "...", "value": "..." }
 *     { "type": "append",       "parent": "...", "node": <node> }
 *     { "type": "insert",       "parent": "...", "index": N, "node": <node> }
 *     { "type": "remove",       "parent": "...", "child": "..." }
 *     { "type": "meta",         "title": "...", "icon": "..." }
 *
 *   <node>:
 *     { "id": "...",
 *       "kind": "container|text|heading|button|input|checkbox|select|image|separator|form",
 *       "level": 1,             (heading only)
 *       "text": "..." | null,
 *       "value": "..." | null,
 *       "disabled": false,
 *       "visible": true,
 *       "options": [...]        (select only)
 *       "attrs": { "key": "val", ... },
 *       "children": [<node>, ...] }
 *
 *   Client -> Server:
 *     { "type": "event", "id": "...", "event": "click" }
 *     { "type": "event", "id": "...", "event": "input",  "value": "..." }
 *     { "type": "event", "id": "...", "event": "change", "value": "..." }
 *     { "type": "event", "id": "form_id", "event": "submit",
 *       "form_data": { "child_id": "value", ... } }
 */

#ifndef WEBGUI_HTML_H
#define WEBGUI_HTML_H

static const char wg__html_page[] =
"<!DOCTYPE html>\n"
"<html lang=\"en\">\n"
"<head>\n"
"<meta charset=\"utf-8\">\n"
"<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\n"
"<title>WebGUI</title>\n"
"<style>\n"
"  :root { color-scheme: light dark; }\n"
"  body {\n"
"    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto,\n"
"                 'Helvetica Neue', Arial, sans-serif;\n"
"    margin: 0; padding: 16px;\n"
"    line-height: 1.5;\n"
"  }\n"
"  button, input, textarea, select {\n"
"    font: inherit;\n"
"    padding: 6px 10px;\n"
"    border-radius: 6px;\n"
"    border: 1px solid #888;\n"
"    background: Canvas; color: CanvasText;\n"
"  }\n"
"  button { cursor: pointer; }\n"
"  button:disabled, input:disabled, textarea:disabled, select:disabled {\n"
"    opacity: 0.5; cursor: not-allowed;\n"
"  }\n"
"  textarea { min-width: 200px; min-height: 60px; resize: vertical; }\n"
"  hr { border: 0; border-top: 1px solid #8884; margin: 12px 0; }\n"
"  h1,h2,h3,h4,h5,h6 { margin: 0.4em 0; }\n"
"  form { display: contents; }\n"
"  #__wg_status__ {\n"
"    position: fixed; top: 8px; right: 8px;\n"
"    padding: 4px 8px; border-radius: 4px;\n"
"    background: #f00; color: #fff; font-size: 12px;\n"
"    display: none;\n"
"  }\n"
"</style>\n"
"</head>\n"
"<body>\n"
"<div id=\"__wg_root__\"></div>\n"
"<div id=\"__wg_status__\">disconnected</div>\n"
"<script>\n"
"(function(){\n"
"  'use strict';\n"
"  var elements = new Map();   // id -> wrapper {dom, control, kind, ...}\n"
"  var ws = null;\n"
"  var status = document.getElementById('__wg_status__');\n"
"  var rootEl = document.getElementById('__wg_root__');\n"
"\n"
"  function showStatus(msg) {\n"
"    if (msg) { status.textContent = msg; status.style.display = 'block'; }\n"
"    else { status.style.display = 'none'; }\n"
"  }\n"
"\n"
"  function send(obj) {\n"
"    if (ws && ws.readyState === 1) ws.send(JSON.stringify(obj));\n"
"  }\n"
"\n"
"  function findForm(el) {\n"
"    while (el && el !== rootEl) {\n"
"      if (el.__wg && el.__wg.kind === 'form') return el.__wg;\n"
"      el = el.parentNode;\n"
"    }\n"
"    return null;\n"
"  }\n"
"\n"
"  function collectForm(form) {\n"
"    var out = {};\n"
"    function walk(rec) {\n"
"      var d = rec.dom;\n"
"      if (rec !== form) {\n"
"        if (rec.kind === 'input') out[rec.id] = rec.control.value;\n"
"        else if (rec.kind === 'checkbox') out[rec.id] = rec.control.checked ? 'true' : 'false';\n"
"        else if (rec.kind === 'select') out[rec.id] = rec.control.value;\n"
"      }\n"
"      for (var i=0;i<d.childNodes.length;i++) {\n"
"        var c = d.childNodes[i];\n"
"        if (c.__wg) walk(c.__wg);\n"
"      }\n"
"    }\n"
"    walk(form);\n"
"    return out;\n"
"  }\n"
"\n"
"  function wireEvents(rec) {\n"
"    var id = rec.id;\n"
"    if (rec.kind === 'button') {\n"
"      rec.dom.addEventListener('click', function(e){\n"
"        e.preventDefault();\n"
"        if (rec.attrs.role === 'submit') {\n"
"          var form = findForm(rec.dom);\n"
"          if (form) {\n"
"            send({type:'event', id:form.id, event:'submit', form_data:collectForm(form)});\n"
"            return;\n"
"          }\n"
"        }\n"
"        send({type:'event', id:id, event:'click'});\n"
"      });\n"
"    } else if (rec.kind === 'input') {\n"
"      rec.control.addEventListener('input', function(){\n"
"        send({type:'event', id:id, event:'input', value:rec.control.value});\n"
"      });\n"
"      rec.control.addEventListener('change', function(){\n"
"        send({type:'event', id:id, event:'change', value:rec.control.value});\n"
"      });\n"
"      rec.control.addEventListener('keydown', function(e){\n"
"        if (e.key === 'Enter' && rec.attrs && rec.attrs.type !== 'multiline') {\n"
"          var form = findForm(rec.dom);\n"
"          if (form) {\n"
"            e.preventDefault();\n"
"            send({type:'event', id:form.id, event:'submit', form_data:collectForm(form)});\n"
"          }\n"
"        }\n"
"      });\n"
"    } else if (rec.kind === 'checkbox') {\n"
"      rec.control.addEventListener('change', function(){\n"
"        send({type:'event', id:id, event:'change', value:rec.control.checked?'true':'false'});\n"
"      });\n"
"    } else if (rec.kind === 'select') {\n"
"      rec.control.addEventListener('change', function(){\n"
"        send({type:'event', id:id, event:'change', value:rec.control.value});\n"
"      });\n"
"    }\n"
"  }\n"
"\n"
"  function applyAttr(rec, key, val) {\n"
"    rec.attrs[key] = val;\n"
"    var dom = rec.dom, ctl = rec.control;\n"
"    if (key === 'class') { dom.className = val; return; }\n"
"    if (key === 'style') { dom.setAttribute('style', val); return; }\n"
"    if (key === 'placeholder' && 'placeholder' in ctl) { ctl.placeholder = val; return; }\n"
"    if (key === 'src' && rec.kind === 'image') { dom.src = val; return; }\n"
"    if (key === 'role') { dom.setAttribute('role', val); return; }\n"
"    if (key === 'min' || key === 'max' || key === 'step') {\n"
"      if (ctl.setAttribute) ctl.setAttribute(key, val);\n"
"      return;\n"
"    }\n"
"    if (key === 'type') {\n"
"      // Type is already set during build; skip.\n"
"      // retypeInput is only needed for runtime type changes via set_attr.\n"
"      if (rec.attrs.type && rec.attrs.type !== val) retypeInput(rec, val);\n"
"      return;\n"
"    }\n"
"    if (key[0] === '_') return;  // reserved for client-side flags\n"
"    dom.setAttribute(key, val);\n"
"  }\n"
"\n"
"  function retypeInput(rec, type) {\n"
"    var oldCtl = rec.control;\n"
"    var oldVal = oldCtl ? oldCtl.value : '';\n"
"    var oldPH  = oldCtl ? oldCtl.placeholder : '';\n"
"    var oldDis = oldCtl ? oldCtl.disabled : false;\n"
"    var newCtl;\n"
"    if (type === 'multiline') {\n"
"      newCtl = document.createElement('textarea');\n"
"      newCtl.rows = oldCtl && oldCtl.rows ? oldCtl.rows : 3;\n"
"    } else {\n"
"      newCtl = document.createElement('input');\n"
"      newCtl.type = (type==='password'||type==='number'||type==='text'||\n"
"                     type==='email'||type==='tel'||type==='url') ? type : 'text';\n"
"    }\n"
"    newCtl.value = oldVal;\n"
"    if (oldPH) newCtl.placeholder = oldPH;\n"
"    newCtl.disabled = oldDis;\n"
"    if (oldCtl.parentNode) oldCtl.parentNode.replaceChild(newCtl, oldCtl);\n"
"    rec.control = newCtl;\n"
"    wireEvents(rec);\n"
"  }\n"
"\n"
"  function build(node) {\n"
"    var dom, ctl;\n"
"    var attrs = node.attrs || {};\n"
"    switch (node.kind) {\n"
"      case 'container': dom = document.createElement('div'); ctl = dom; break;\n"
"      case 'text':      dom = document.createElement('span'); ctl = dom; break;\n"
"      case 'heading': {\n"
"        var lvl = node.level|0; if (lvl<1) lvl=1; if (lvl>6) lvl=6;\n"
"        dom = document.createElement('h'+lvl); ctl = dom; break;\n"
"      }\n"
"      case 'button': dom = document.createElement('button'); ctl = dom;\n"
"                     dom.type = 'button'; break;\n"
"      case 'input': {\n"
"        var t = attrs.type || 'text';\n"
"        if (t === 'multiline') { ctl = document.createElement('textarea'); }\n"
"        else {\n"
"          ctl = document.createElement('input');\n"
"          ctl.type = (t==='password'||t==='number') ? t : 'text';\n"
"        }\n"
"        dom = ctl;\n"
"        break;\n"
"      }\n"
"      case 'checkbox': {\n"
"        dom = document.createElement('label');\n"
"        ctl = document.createElement('input'); ctl.type = 'checkbox';\n"
"        dom.appendChild(ctl);\n"
"        var lbl = document.createElement('span');\n"
"        lbl.textContent = node.text || '';\n"
"        lbl.style.marginLeft = '6px';\n"
"        dom.appendChild(lbl);\n"
"        dom.__wg_label = lbl;\n"
"        break;\n"
"      }\n"
"      case 'select': {\n"
"        ctl = document.createElement('select');\n"
"        var opts = node.options || [];\n"
"        for (var i=0;i<opts.length;i++) {\n"
"          var o = document.createElement('option');\n"
"          o.value = o.textContent = String(opts[i]);\n"
"          ctl.appendChild(o);\n"
"        }\n"
"        dom = ctl;\n"
"        break;\n"
"      }\n"
"      case 'image': dom = document.createElement('img'); ctl = dom;\n"
"                    if (attrs.src) dom.src = attrs.src;\n"
"                    break;\n"
"      case 'separator': dom = document.createElement('hr'); ctl = dom; break;\n"
"      case 'form': dom = document.createElement('div');\n"
"                   dom.setAttribute('data-wg-form','1'); ctl = dom; break;\n"
"      default: dom = document.createElement('div'); ctl = dom; break;\n"
"    }\n"
"    var rec = {\n"
"      id: node.id, kind: node.kind, dom: dom, control: ctl,\n"
"      attrs: {}, level: node.level || 0\n"
"    };\n"
"    dom.__wg = rec;\n"
"    if (node.kind !== 'checkbox' && node.text != null) {\n"
"      if (rec.kind === 'image') dom.alt = node.text;\n"
"      else if (rec.kind === 'text' || rec.kind === 'heading' || rec.kind === 'button') {\n"
"        dom.textContent = node.text;\n"
"      }\n"
"    }\n"
"    if (node.value != null && 'value' in ctl) ctl.value = node.value;\n"
"    if (node.disabled) { if ('disabled' in ctl) ctl.disabled = true; }\n"
"    if (node.visible === false) dom.style.display = 'none';\n"
"    Object.keys(attrs).forEach(function(k){ applyAttr(rec, k, attrs[k]); });\n"
"    wireEvents(rec);\n"
"    elements.set(node.id, rec);\n"
"    var children = node.children || [];\n"
"    for (var i=0;i<children.length;i++) dom.appendChild(build(children[i]).dom);\n"
"    return rec;\n"
"  }\n"
"\n"
"  function unregister(rec) {\n"
"    elements.delete(rec.id);\n"
"    var d = rec.dom;\n"
"    for (var i=0;i<d.childNodes.length;i++) {\n"
"      var c = d.childNodes[i];\n"
"      if (c.__wg) unregister(c.__wg);\n"
"    }\n"
"  }\n"
"\n"
"  function apply(msg) {\n"
"    if (msg.type === 'render') {\n"
"      if (msg.title) document.title = msg.title;\n"
"      if (msg.icon) setIcon(msg.icon);\n"
"      rootEl.innerHTML = '';\n"
"      elements.clear();\n"
"      if (msg.tree) rootEl.appendChild(build(msg.tree).dom);\n"
"      return;\n"
"    }\n"
"    if (msg.type === 'meta') {\n"
"      if (msg.title) document.title = msg.title;\n"
"      if (msg.icon) setIcon(msg.icon);\n"
"      return;\n"
"    }\n"
"    var rec = elements.get(msg.id || msg.parent);\n"
"    if (msg.type === 'set_text') {\n"
"      if (!rec) return;\n"
"      if (rec.kind === 'checkbox') rec.dom.__wg_label.textContent = msg.value || '';\n"
"      else if (rec.kind === 'image') rec.dom.alt = msg.value || '';\n"
"      else rec.dom.textContent = msg.value || '';\n"
"    } else if (msg.type === 'set_value') {\n"
"      if (!rec) return;\n"
"      if ('value' in rec.control) rec.control.value = msg.value || '';\n"
"    } else if (msg.type === 'set_disabled') {\n"
"      if (!rec) return;\n"
"      if ('disabled' in rec.control) rec.control.disabled = !!msg.value;\n"
"    } else if (msg.type === 'set_visible') {\n"
"      if (!rec) return;\n"
"      rec.dom.style.display = msg.value ? '' : 'none';\n"
"    } else if (msg.type === 'set_attr') {\n"
"      if (!rec) return;\n"
"      applyAttr(rec, msg.key, msg.value);\n"
"    } else if (msg.type === 'append') {\n"
"      var p = elements.get(msg.parent);\n"
"      if (!p) return;\n"
"      p.dom.appendChild(build(msg.node).dom);\n"
"    } else if (msg.type === 'insert') {\n"
"      var p2 = elements.get(msg.parent);\n"
"      if (!p2) return;\n"
"      var nrec = build(msg.node);\n"
"      var idx = msg.index|0;\n"
"      var ref = p2.dom.children[idx];\n"
"      if (ref) p2.dom.insertBefore(nrec.dom, ref);\n"
"      else p2.dom.appendChild(nrec.dom);\n"
"    } else if (msg.type === 'remove') {\n"
"      var ch = elements.get(msg.child);\n"
"      if (!ch) return;\n"
"      if (ch.dom.parentNode) ch.dom.parentNode.removeChild(ch.dom);\n"
"      unregister(ch);\n"
"    }\n"
"  }\n"
"\n"
"  function setIcon(url) {\n"
"    var link = document.querySelector(\"link[rel='icon']\");\n"
"    if (!link) { link = document.createElement('link'); link.rel='icon'; document.head.appendChild(link); }\n"
"    link.href = url;\n"
"  }\n"
"\n"
"  function connect() {\n"
"    var proto = location.protocol === 'https:' ? 'wss:' : 'ws:';\n"
"    ws = new WebSocket(proto + '//' + location.host + '/');\n"
"    ws.onopen = function(){ showStatus(''); };\n"
"    ws.onmessage = function(ev){\n"
"      var msg;\n"
"      try { msg = JSON.parse(ev.data); } catch(e) { return; }\n"
"      apply(msg);\n"
"    };\n"
"    ws.onclose = function(){ showStatus('disconnected'); setTimeout(connect, 1000); };\n"
"    ws.onerror = function(){ /* onclose follows */ };\n"
"  }\n"
"  connect();\n"
"})();\n"
"</script>\n"
"</body>\n"
"</html>\n";

#endif /* WEBGUI_HTML_H */
